"""tests/test_ratchet_lock.py — generated by adopt/install-ratchet.sh (SPEC INV-172). Do not hand-edit
the SEEDED_* constants; they are the size measured at adoption time. The ratchet only ever tightens:
the suite reds when a gated doc grows past the seeded size, and reds when scripts/spec-debt-cap.json
is raised past what was seeded here — raising a cap for real means editing this file, on purpose,
reviewed.
"""
import json
import os
import subprocess

SEEDED_STYLE_ERRORS = 0
SEEDED_REDUNDANCY_OPEN = 29
GATED_DOCS = ['docs/SPEC.md', 'docs/ARCHITECTURE.md', 'docs/TEST_MATRIX.md']
TIER = 'universal'


def _host_root():
    out = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"], capture_output=True, text=True, check=True
    )
    return out.stdout.strip()


def _cap():
    root = _host_root()
    with open(os.path.join(root, "scripts", "spec-debt-cap.json"), encoding="utf-8") as f:
        return json.load(f)


def test_caps_never_raised_past_seed():
    cap = _cap()
    assert cap["max_style_errors"] <= SEEDED_STYLE_ERRORS, (
        "max_style_errors raised above the seeded %d — raising the cap for real means editing "
        "this generated test" % SEEDED_STYLE_ERRORS)
    assert cap["max_redundancy_open"] <= SEEDED_REDUNDANCY_OPEN, (
        "max_redundancy_open raised above the seeded %d — raising the cap for real means editing "
        "this generated test" % SEEDED_REDUNDANCY_OPEN)
    assert cap["max_waivers"] <= 0


def test_style_errors_within_cap():
    root = _host_root()
    cap = _cap()
    total = 0
    for doc in GATED_DOCS:
        out = subprocess.run(
            ["python3", os.path.join(root, "scripts", "spec-style-lint.py"), "--tier", TIER,
             os.path.join(root, doc)],
            capture_output=True, text=True,
        )
        last_line = out.stdout.strip().splitlines()[-1]
        total += json.loads(last_line)["errors"]
    assert total <= cap["max_style_errors"], (
        "style errors grew to %d, above the cap %d" % (total, cap["max_style_errors"]))


def test_redundancy_open_within_cap():
    root = _host_root()
    cap = _cap()
    total = 0
    for doc in GATED_DOCS:
        out = subprocess.run(
            ["python3", os.path.join(root, "scripts", "spec-redundancy-precheck.py"),
             os.path.join(root, doc)],
            capture_output=True, text=True,
        )
        last_line = out.stdout.strip().splitlines()[-1]
        total += json.loads(last_line)["open"]
    assert total <= cap["max_redundancy_open"], (
        "redundancy-open grew to %d, above the cap %d" % (total, cap["max_redundancy_open"]))
