#!/usr/bin/env python3
"""catalog.py — the VIEW over the global library store.

`library.py` is the store (deposit/list/clean + the pure metric/version helpers); this module is the
front-end: it reads `index.json` and renders ONE self-contained, offline `index.html` — the home base
for a producer's whole body of work. Flat, sortable, searchable table; each row is a TRACK, shown at its
NEWEST version (D-INV-35 — older versions live only in that track's per-widget version plaque, INV-11),
with a coloured mini-arc, the spec numbers, mood/style tags, and the delta vs the prior version. The catalog is a LOCAL index (INV-17): both the title link
(`_open_href`) and the play button (`_mix_uri_for`) resolve to an absolute `file://` in the ORIGINAL
run dir, where the widget's stems/mix live — the deposited library copy is stem-less. NOT a publishable
/ GitHub Pages artifact; revisit (KI-4 option b) only if the library is ever published.

  catalog.py build [--open]      # regenerate ~/.track-coach/library/index.html

Auto-regenerated by `track_analyzer.py build` after every deposit; also runnable on demand.
Pure stdlib. `render_catalog_html(entries)` is pure (no filesystem) so it's unit-tested.
"""
from __future__ import annotations
import argparse
import html
import json
import re
import subprocess
import sys
from pathlib import Path
from urllib.parse import quote

import library  # same scripts/ dir; reuses load_index + the pure metric/version helpers
import build_widget  # for TC_VERSION only (stdlib-only import) — stamp the catalog with its version
import fingerprints as FP  # 14-axis extraction + z-normalisation
import similarity_columns as SC  # leans_toward / nearest_own geometry

# Path to the pre-built reference-direction centroids + normalization params.
_DATA_DIR = Path(__file__).resolve().parent.parent / "data"
_REF_FILE = _DATA_DIR / "reference_directions.json"

# Level → colour for the two similarity columns (owner decision 2026-06-29).
# Reference column: close=green, mid=amber, far → "no close direction yet" (grey, no red).
# Sibling column:   close=green, mid=amber, far=red (allowed as last-resort per F-INV-1).
_SIM_COL = {"close": "#2e9e5b", "mid": "#d8932a", "far": "#c2503d"}

# Greyscale-safe closeness glyph (D-INV-26): ●●● close / ●●○ mid / ●○○ far. ONE scheme, shared by
# BOTH similarity columns (§D reference + §F own-library) so the cue reads uniformly and survives
# greyscale, print, and colour-blind reading — the filled-vs-hollow SHAPE carries it, not the colour.
_CLOSENESS_DOTS = {"close": "●●●", "mid": "●●○", "far": "●○○"}
# The closeness level named in plain words — the non-colour, non-shape cue (D-INV-26). An unknown
# level falls back to "far" so the helper never raises and reads consistently across both columns.
_CLOSENESS_WORD = {"close": "close", "mid": "mild", "far": "far"}


def _closeness_word(level: str) -> str:
    return _CLOSENESS_WORD.get(level, "far")


def _closeness_dots(level: str) -> str:
    """The 3-tier greyscale-safe closeness glyph for a level (D-INV-26), carried alongside the plain
    closeness WORD. The dots span is aria-hidden (the colour-independent visual redundancy); a
    screen-reader-only span names the closeness in words so assistive tech and colour-blind readers
    get the level without the colour or the dot shape. The `title` surfaces the same word on hover."""
    word = _closeness_word(level)
    return (f'<span class="dot-tier" aria-hidden="true" title="closeness: {word}">'
            f'{_CLOSENESS_DOTS.get(level, "●○○")}</span>'
            f'<span class="sr-only"> ({word} closeness)</span>')

PALETTE = {  # slim copy of the build_widget dark theme so the catalog feels like the widgets
    # SPEC §I.0 DS-INV-1/2: canon = the WIDGET values; these MUST stay byte-equal on shared roles
    # (test_design_tokens.py guards it). `line`/`ink` drifted here historically and were re-synced.
    "bg": "#0c0e14", "panel": "#141822", "panel2": "#1b2030", "line": "#262c3c",
    "ink": "#e8ecf5", "ink_dim": "#aeb6c8", "muted": "#8b94a8", "wob": "#a78bfa", "good": "#46d39a",
    "bad": "#ff6b6b", "bright": "#ffd166",
}


def _fmt_len(s):
    if not isinstance(s, (int, float)):
        return "—"
    return f"{int(s) // 60}:{int(s) % 60:02d}"


def _fmt_date(stamp):
    """`2026-06-18_0748` → `2026-06-18 07:48`; anything else passes through. Uses rsplit on the LAST
    underscore so a stamp that happens to carry more underscores (malformed deposit) formats instead
    of crashing — `d, t = s.split('_')` used to raise 'too many values to unpack'."""
    s = str(stamp or "")
    if "_" in s:
        d, t = s.rsplit("_", 1)
        if len(t) == 4 and t.isdigit():
            return f"{d} {t[:2]}:{t[2:]}"
    return s


def _is_date_shaped(stamp) -> bool:
    """True when a stamp is a real `YYYY-MM-DD[_HHMM]` date, not a folder-slug carried
    into the stamp slot (e.g. `Total_Reboot_Wobble_Drift_v0.6.2`)."""
    return bool(re.match(r"^\d{4}-\d{2}-\d{2}(_\d{4})?$", str(stamp or "")))


def _display_date(e) -> str:
    """The Date CELL value — never a raw dev slug (turnkey: no dev-internal on the surface).

    A date-shaped stamp formats via `_fmt_date`; otherwise the stamp is a folder-slug (a run
    dir that didn't follow `<track>/<stamp>`), so we fall back to a real `analyzed_at` date if
    present, else `—`. `_fmt_date`'s pure passthrough (INV-13) is untouched — this is a
    caller-side display choice."""
    stamp = e.get("stamp")
    if _is_date_shaped(stamp):
        return _fmt_date(stamp)
    analyzed = str(e.get("analyzed_at") or "")
    m = re.match(r"(\d{4}-\d{2}-\d{2})[ T](\d{2}):(\d{2})", analyzed)
    if m:
        return f"{m.group(1)} {m.group(2)}:{m.group(3)}"
    if re.match(r"^\d{4}-\d{2}-\d{2}$", analyzed):
        return analyzed
    return "—"


def _fmt_num(x, suffix="", dp=0):
    if not isinstance(x, (int, float)):
        return "—"
    return (f"{x:.{dp}f}" if dp else f"{x:.0f}") + suffix


def _delta_html(delta, key, suffix=""):
    """↑/↓ chip vs the previous version (green=down for LUFS isn't implied; just direction)."""
    d = (delta or {}).get(key)
    if not isinstance(d, (int, float)) or abs(d) < 0.05:
        return ""
    arrow = "▲" if d > 0 else "▼"
    return f'<span class="delta">{arrow}{abs(d):.1f}{suffix}</span>'


def arc_svg(arc, w=130, h=30):
    """Inline-SVG sparkline of the energy curve (the Simple hero curve, tiny). Pure string.

    Legacy fallback for OLD index entries that predate the richer row signature (no per-curve /
    tonal data). New entries render the full `signature_svg` instead."""
    vals = [v for v in (arc or []) if isinstance(v, (int, float))]
    if not vals:
        return '<span class="noarc">—</span>'
    n = len(vals)
    pts = [((i / (n - 1) * w if n > 1 else 0), h - v * (h - 3) - 1.5) for i, v in enumerate(vals)]
    line = " ".join(f"{x:.1f},{y:.1f}" for x, y in pts)
    area = f"0,{h} {line} {w},{h}"
    return (f'<svg class="arc" viewBox="0 0 {w} {h}" preserveAspectRatio="none" aria-hidden="true">'
            f'<polygon points="{area}" fill="url(#ag)"/>'
            f'<polyline points="{line}" fill="none" stroke="{PALETTE["wob"]}" stroke-width="1.5"/></svg>')


# ── catalog ROW SIGNATURE (D ribbon + 9-band tonal strip) ───────────────────────────────────
# Decided 2026-06-19 (see memory track-catalog-viz / NEXT_STEPS): one shape that carries real,
# measured-non-redundant info per track, and is fully visible by TAP — no hover, no tooltip.
#   TOP   = spectral ribbon, x = TIME : height=energy, line+fill colour=brightness, weight=density.
#   BOTTOM= 9-band tonal strip, x = FREQUENCY : the widget's own low-red→mid-green→high-blue ramp,
#           bar height ∝ loudness, flagged bands (|dev_db|≥4) brightened.
# The two axes (time vs frequency) are deliberately kept apart by a gap + divider so the cell reads
# as "shape over time" + "spectrum", not one plot.
SIG_W, RIB_H, STRIP_H, GAPV = 168, 30, 12, 5
SIG_H = RIB_H + GAPV + STRIP_H
_DEEP, _GOLD, _COOL = (108, 92, 255), (255, 209, 102), (120, 230, 220)


def _norm(v):
    v = [x for x in v if isinstance(x, (int, float))]
    if not v:
        return []
    lo, hi = min(v), max(v)
    r = (hi - lo) or 1.0
    return [(x - lo) / r for x in v]


def _lerp(a, b, t):
    return tuple(round(a[i] + (b[i] - a[i]) * t) for i in range(3))


def _hexc(c):
    return "#%02x%02x%02x" % tuple(max(0, min(255, int(x))) for x in c)


def _bright_col(t):
    """brightness ramp: deep-violet → gold (t<0.6) → cool teal (t≥0.6)."""
    return _hexc(_lerp(_DEEP, _GOLD, t / 0.6)) if t < 0.6 else _hexc(_lerp(_GOLD, _COOL, (t - 0.6) / 0.4))


def _band_col(t):
    """widget's frequency ramp (build_widget.py): low red → mid green → high blue."""
    if t < 0.5:
        tt = t * 2
        return (255 - tt * (255 - 76), 78 + tt * (214 - 78), 80 + tt * (140 - 80))
    tt = (t - 0.5) * 2
    return (76 - tt * (76 - 80), 214 - tt * (214 - 168), 140 + tt * (255 - 140))


def _poly(P):
    return " ".join(f"{x:.1f},{y:.1f}" for x, y in P)


def _ribbon(energy, brightness, density, uid):
    """The time-shape ribbon. Returns SVG inner string (defs + polygon + polyline), or '' if empty."""
    e = _norm(energy)
    if not e:
        return ""
    b = _norm(brightness) or [0.5] * len(e)
    d = _norm(density) or [0.4] * len(e)
    n = len(e)
    if len(b) != n:  # guard: align colour to the energy curve length
        b = (b + [b[-1]] * n)[:n] if b else [0.5] * n
    dens_avg = (sum(d) / len(d)) if d else 0.4
    pts = [(i / (n - 1) * SIG_W if n > 1 else 0, RIB_H - 2 - c * (RIB_H - 4)) for i, c in enumerate(e)]
    area = f"0,{RIB_H - 2} " + _poly(pts) + f" {SIG_W},{RIB_H - 2}"
    stops = "".join(f'<stop offset="{i / (n - 1) * 100:.1f}%" stop-color="{_bright_col(b[i])}"/>'
                    for i in range(n)) if n > 1 else f'<stop offset="0%" stop-color="{_bright_col(b[0])}"/>'
    fstops = "".join(f'<stop offset="{i / (n - 1) * 100:.1f}%" stop-color="{_bright_col(b[i])}" stop-opacity="0.30"/>'
                     for i in range(n)) if n > 1 else f'<stop offset="0%" stop-color="{_bright_col(b[0])}" stop-opacity="0.30"/>'
    lw = 1.2 + dens_avg * 1.7
    return (f'<defs><linearGradient id="r{uid}" x1="0" x2="1">{stops}</linearGradient>'
            f'<linearGradient id="rf{uid}" x1="0" x2="1">{fstops}</linearGradient></defs>'
            f'<polygon points="{area}" fill="url(#rf{uid})"/>'
            f'<polyline points="{_poly(pts)}" fill="none" stroke="url(#r{uid})" '
            f'stroke-width="{lw:.1f}" stroke-linejoin="round"/>')


def _tonal_strip(tonal):
    """The 9-band spectrum strip (x=frequency). Returns SVG inner string, or '' if no tonal data."""
    rel = [b.get("rel_db", 0) for b in tonal if isinstance(b, dict)]
    dev = [b.get("dev_db", 0) for b in tonal if isinstance(b, dict)]
    if not rel:
        return ""
    lo = min(rel)
    span = max(8.0, -lo)
    n = len(rel)
    gap = 2
    bw = (SIG_W - gap * (n - 1)) / n
    y0 = RIB_H + GAPV
    out = f'<line x1="0" y1="{y0:.1f}" x2="{SIG_W}" y2="{y0:.1f}" stroke="{PALETTE["line"]}" stroke-width="0.6"/>'
    for i, vdb in enumerate(rel):
        x = i * (bw + gap)
        h = max(1.5, (1 - (-vdb / span)) * STRIP_H)  # louder band (rel_db→0) = taller bar
        c = _band_col(i / (n - 1) if n > 1 else 0)
        hot = i < len(dev) and isinstance(dev[i], (int, float)) and abs(dev[i]) >= 4
        op = 0.95 if hot else 0.6
        out += (f'<rect x="{x:.1f}" y="{y0 + (STRIP_H - h):.1f}" width="{bw:.1f}" height="{h:.1f}" '
                f'fill="rgb({int(c[0])},{int(c[1])},{int(c[2])})" opacity="{op}"/>')
    return out


def signature_svg(e, uid=0, playable=False):
    """Full catalog row signature for index entry `e`: spectral ribbon over a 9-band tonal strip.

    Degrades gracefully: ribbon-only when there's no `tonal_balance` (e.g. older entries that still
    have curves); legacy `arc` sparkline when there are no curves at all; '—' when nothing. PURE.

    `playable` (a web mix exists for this row) overlays a click-to-seek area + a playhead line on
    the TIME axis (the ribbon, top) only — never the frequency strip — so the row doubles as a
    one-button preview scrubber (2026-06-20: the scrubber runs along the time graph, staying off the frequency axis)."""
    energy = e.get("energy") or []
    rib = _ribbon(energy, e.get("brightness") or [], e.get("density") or [], uid)
    if not rib:
        return arc_svg(e.get("arc"))  # no per-curve data → legacy sparkline (or '—')
    strip = _tonal_strip(e.get("tonal_balance") or [])
    h = SIG_H if strip else RIB_H
    if playable:
        scrub = (f'<rect class="scrub" x="0" y="0" width="{SIG_W}" height="{RIB_H}" fill="transparent"/>'
                 f'<line class="ph" x1="0" y1="0" x2="0" y2="{RIB_H}" stroke="{PALETTE["ink"]}" '
                 f'stroke-width="1.4" visibility="hidden"/>')
        return (f'<svg class="sig play" viewBox="0 0 {SIG_W} {h}" preserveAspectRatio="none">'
                f'{rib}{strip}{scrub}</svg>')
    return (f'<svg class="sig" viewBox="0 0 {SIG_W} {h}" preserveAspectRatio="none" aria-hidden="true">'
            f'{rib}{strip}</svg>')


def _lean_cell(leans, widget_href=None, reason=None, missing=None) -> str:
    """Render the 'leans toward' (reference) TD for a row (§D.10.1).

    Accepts a list of up to 3 Lean objects (nearest-first, CLOSE/MID only — FAR never
    reaches here, leans_toward_topk already excluded them). Each direction is a coloured
    clickable link stacked vertically. No red for the reference column — owner decision 2026-06-29.

    Empty state is THREE-WAY (D-INV-22 + D-INV-22-completeness) and uses THIS column's own phrases,
    never the siblings column's 'no similar tracks' (Fable audit 2026-07-03):
      • quick-only row (R_QUICK) → 'full analysis only' — quick never promised a reference (D-INV-20/22);
      • full run missing axes (R_MISSING) → 'can't compare — ⟨missing signals⟩', never a fabricated
        nearest (D-INV-22-completeness) — the missing measurements named inline;
      • full run, no close direction (R_NO_DIRECTION / default) → 'no close direction yet' (SPEC §D).

    widget_href: the row's own widget URL (from _open_href). Direction links carry the
    ONE-SHOT ENTRY PAIR `?direction=⟨URL-encoded name⟩#detailed` (D-INV-37, wired s59):
    the widget's entry reader focuses that direction's tab and scrolls the panel into
    view; `#detailed` is the §B.15 one-shot view override — the panel is Simple-hidden
    (INV-18/22), so entry must ride it. Neither half persists anything.
    When None, falls back to '#refRead' (in-page no-op but never the dead bare '#')."""
    if not leans:
        if reason == SC.R_QUICK:
            msg = "full analysis only"
        elif reason == SC.R_MISSING:
            names = html.escape(SC.signals_phrase(missing or []))  # only the dynamic names need escaping
            msg = f"can't compare — {names}" if names else "can't compare"
        else:  # R_NO_DIRECTION (and the graceful default)
            msg = "no close direction yet"
        return f'<td class="c-sim c-lean"><span class="sim-none">{msg}</span></td>'
    chips = ""
    for lean in leans:
        col = _SIM_COL.get(lean.level, "#8b94a8")
        dn = html.escape(lean.direction)
        dir_href = (html.escape(f"{widget_href}?direction={quote(lean.direction)}#detailed")
                    if widget_href else "#refRead")
        chips += (f'<a class="sim-dir" href="{dir_href}" style="color:{col}" '
                  f'title="closeness: {_closeness_word(lean.level)}">'
                  f'{_closeness_dots(lean.level)}{dn}</a>')
    return f'<td class="c-sim c-lean">{chips}</td>'


def _siblings_cell(siblings, title_map: dict, href_map: dict, reason=None, missing=None) -> str:
    """Render the 'similar in your library' TD for a row.
    Up to 3 siblings, each as a coloured chip link. FAR siblings are allowed here (F-INV-1).
    Uses title_map for display labels.

    The chip is IN-PAGE NAVIGATION, not a widget link (F-INV-4 / D-INV-28): its href is the sibling
    row's `#row-<slug>` anchor and the catalog scrolls+highlights that row on click — the click
    changes no analysis state. (An own sibling scrolls; a reference DIRECTION opens the widget — the
    two are deliberately different, D-INV-28.)

    Empty state is THREE-WAY (F-INV-5/6/7), never a bare '—':
      • quick-only row (R_QUICK) → 'full analysis only' (F-INV-5);
      • full run missing axes (R_MISSING) → 'can't compare — ⟨missing signals⟩' (F-INV-6);
      • computed but no other placeable track (R_NO_COMPARISON / default) → 'no comparison yet' (F-INV-7)."""
    if not siblings:
        if reason == SC.R_QUICK:
            msg = "full analysis only"
        elif reason == SC.R_MISSING:
            names = html.escape(SC.signals_phrase(missing or []))  # only the dynamic names need escaping
            msg = f"can't compare — {names}" if names else "can't compare"
        else:  # R_NO_COMPARISON (and the graceful default) — never a bare dash
            msg = "no comparison yet"
        return f'<td class="c-sim c-sibs"><span class="sim-none">{msg}</span></td>'
    chips = ""
    for sib in siblings:
        col = _SIM_COL.get(sib.level, "#8b94a8")  # unknown level → neutral grey, never a KeyError
        label = html.escape(title_map.get(sib.track) or sib.track.replace("_", " "))
        href = "#" + _row_id(sib.track)           # F-INV-4: scroll to the sibling's row, not its widget
        chips += (f'<a class="sib-chip" href="{html.escape(href)}" data-scroll-row="{html.escape(_row_id(sib.track))}" '
                  f'title="closeness: {_closeness_word(sib.level)}" '
                  f'style="border-color:{col}66;color:{col}">{_closeness_dots(sib.level)}{label}</a>')
    return f'<td class="c-sim c-sibs">{chips}</td>'


def _tag_chips(mood, style, source):
    chips = "".join(f'<span class="tag mood">{html.escape(str(t))}</span>' for t in (mood or []))
    chips += "".join(f'<span class="tag style">{html.escape(str(t))}</span>' for t in (style or []))
    if not chips:
        return '<span class="noarc">—</span>'
    if source == "heuristic":  # mark drafts so an un-reviewed guess never reads as fact
        chips += '<span class="tag draft" title="auto-detected style — not yet reviewed">guess</span>'
    return chips


def _widget_version(e):
    """The TC_VERSION the linked widget was built on. Prefer the value stored in the index entry at
    deposit time (`tc_version`) — filename-INDEPENDENT, so a stale link is caught even when the filename
    carries no version or a musical one like `v2` (INV-12 option-b / KI-7). Fall back to parsing the
    widget filename (`…_vX.Y.Z.html`) for entries deposited before that field existed. None when neither
    is available — don't cry wolf. PURE. Used to flag a STALE catalog row (INV-12 / KI-1)."""
    tv = (e.get("tc_version") or "").strip()
    if re.fullmatch(r"\d+\.\d+\.\d+", tv):
        return tv
    m = re.search(r"_v(\d+\.\d+\.\d+)\.html$", str(e.get("src_widget") or ""))
    return m.group(1) if m else None


def _ver_tuple(s):
    """(major, minor, patch) for an 'X.Y.Z' string — for an ORDERED version compare. () when malformed."""
    try:
        return tuple(int(p) for p in str(s).split("."))
    except (ValueError, AttributeError):
        return ()


def _widget_analysis_version(e):
    """The TC_ANALYSIS_VERSION the linked widget was built on, stored in the index entry at deposit
    (`tc_analysis_version`). None for a widget deposited before analysis-version stamping. PURE.
    This is what the stale check compares (INV-12)."""
    av = e.get("tc_analysis_version")
    if isinstance(av, bool):
        return None
    if isinstance(av, int):
        return av
    if isinstance(av, str) and av.isdigit():
        return int(av)
    return None


def _stale_chip(e):
    """A self-explaining 'older analysis' marker when the row's linked widget is behind the current
    ANALYSIS version (INV-12). A widget that stored its analysis version is compared to it directly; a
    legacy widget (none stored) is judged by its tool-version build stamp against TC_ANALYSIS_BASELINE_TCV,
    which reproduces the pre-rework verdict for entries deposited before stamping. The chip shows the build
    stamp as the recognizable marker so the meaning is visible without hovering (Glossary 'stale' — UI
    clarity fix 2026-06-30). '' when current or unknown (don't cry wolf). A render-only or infrastructure
    release never reaches here, because it leaves the analysis version untouched."""
    wv = _widget_version(e)                  # tool-version build stamp: the display marker + legacy fallback
    av = _widget_analysis_version(e)
    if av is not None:
        stale = av < build_widget.TC_ANALYSIS_VERSION
    elif wv:
        stale = _ver_tuple(wv) < _ver_tuple(build_widget.TC_ANALYSIS_BASELINE_TCV)
    else:
        stale = False
    if stale:
        marker = f"v{wv}" if wv else "an older run"
        return (f'<span class="stale" title="older analysis than the current one — re-analyse to refresh">'
                f'older analysis · {marker} → re-analyse</span>')
    return ""


def _open_href(e, widgets_rel):
    """Where 'open →' points. Prefer the ORIGINAL widget in its run dir — its stems sit next to
    it, so the player actually plays. The library copy is stem-less (a deposit is a single .html),
    so opening it leaves a dead player. Fall back to the relative copy for old entries that predate
    `src_widget` (backward-compat).

    G-INV-14: when ``build_catalog`` detects ``src_run_dir`` is missing on disk, it injects
    ``_lib_href`` into the entry (the library's own HTML copy as a ``file://`` URI). This function
    prefers that over the dead original link. PURE (no filesystem — the probe is in build_catalog).
    """
    # G-INV-14: library HTML copy fallback pre-computed by build_catalog
    if e.get("_lib_href"):
        return e["_lib_href"]
    src_dir, src_widget = e.get("src_run_dir"), e.get("src_widget")
    if src_dir and src_widget:
        return (Path(src_dir) / src_widget).as_uri()  # absolute file:// (encodes spaces/[brackets])
    widget = e.get("widget", "")
    return f"{widgets_rel}/{widget}" if widget else ""


def _row(track, ver, widgets_rel, uid=0, mix_uri=None, title_map=None, href_map=None,
         show_lean=True, show_sib=True):
    e = ver["rep"]
    title = e.get("title") or track.replace("_", " ")
    href = _open_href(e, widgets_rel)
    # The track TITLE is the link into the widget (no separate "open" column any more —
    # 2026-06-20: the open button is unneeded once the title itself is clickable). Whole row tints on
    # hover (CSS) so it reads as clickable; falls back to a plain span when there's no widget.
    ttl = html.escape(str(title))
    title_cell = (f'<a class="ttl" href="{html.escape(href)}">{ttl}</a>' if href
                  else f'<span class="ttl">{ttl}</span>')
    # One-button preview player: only when the original run has a web mix (mix_uri). The button
    # sits left of the title; the scrubber rides the signature ribbon (wired in JS by data-mix).
    play_btn = ('<button class="cplay" type="button" aria-label="Play preview">▶</button>'
                if mix_uri else "")
    # data-* attrs drive client-side sort; numeric ones fall back to -1 so blanks sort last asc
    def num(x):
        return f"{x}" if isinstance(x, (int, float)) else "-1"
    mix_attr = f' data-mix="{html.escape(mix_uri)}"' if mix_uri else ""
    # F-INV-4: a stable per-track row anchor a sibling chip can scroll to (`#row-<slug>`).
    _leans, _lreason, _lmiss = _lean_state(e)
    _sibs, _sreason, _smiss = _sib_state(e)
    lean_td = (_lean_cell(_leans, widget_href=href, reason=_lreason, missing=_lmiss)
               if show_lean else "")
    sib_td = (_siblings_cell(_sibs, title_map or {}, href_map or {}, reason=_sreason, missing=_smiss)
              if show_sib else "")
    return f"""<tr data-track="{html.escape(track.lower())}" data-mode="{html.escape(e.get('mode',''))}"{mix_attr}
      data-version="{html.escape(str(ver['label']))}" data-date="{html.escape(str(e.get('stamp','')))}"
      data-bpm="{num(e.get('bpm'))}" data-key="{html.escape(str(e.get('key') or ''))}"
      data-len="{num(e.get('length_s'))}" data-lufs="{num(e.get('lufs'))}"
      data-energy="{num(e.get('energy_level'))}" id="{html.escape(_row_id(track))}">
 <td class="c-track"><div class="tcell">{play_btn}<span class="tmeta">{title_cell}</span></div></td>
 <td class="c-ver">{html.escape(str(ver['label']))}{'' if ver['n_runs']<2 else f' <span class=runs>×{ver["n_runs"]}</span>'}{_stale_chip(e)}</td>
 <td class="c-date">{html.escape(_display_date(e))}</td>
 <td class="c-sig">{signature_svg(e, uid, playable=bool(mix_uri))}</td>
 <td class="c-num">{_fmt_num(e.get('bpm'))}{_delta_html(ver.get('delta'),'bpm')}</td>
 <td class="c-key">{html.escape(str(e.get('key') or '—'))}</td>
 <td class="c-num">{_fmt_len(e.get('length_s'))}</td>
 <td class="c-num">{_fmt_num(e.get('lufs'),dp=1)}{_delta_html(ver.get('delta'),'lufs')}</td>
 <td class="c-tags">{_tag_chips(e.get('mood_tags'),e.get('style_tags'),e.get('tags_source'))}</td>
 <td class="c-mode"><span class="mode {html.escape(e.get('mode',''))}">{html.escape(e.get('mode',''))}</span></td>
 {lean_td}
 {sib_td}
</tr>"""


# The one-line "verdict" was dropped from the catalog (2026-06-20: the verdict column broke the layout
# and wasn't worth keeping) — it was the widest, most variable column and forced the table off the
# screen. The verdict still lives inside each track's widget; the catalog stays scannable.
# Full column spec (the superset). Each row is (col_id, sort_key, label): `col_id` is the stable
# identity the presence-gate + responsive shedding key off (never a fixed nth-child), `sort_key`
# drives client sort (None = not sortable). The two similarity columns ("lean"/"sib") are DROPPED
# per-render when no version carries their data (D-INV-22 / F-INV-7); everything else always renders.
_COLUMNS = [
    ("track", "track", "Track"), ("version", "version", "Version"), ("date", "date", "Date"),
    ("sig", None, "Signature"), ("bpm", "bpm", "BPM"), ("key", "key", "Key"),
    ("len", "len", "Length"), ("lufs", "lufs", "LUFS"),
    ("tags", None, "Mood / style"), ("mode", "mode", "Analysis"),
    ("lean", None, "Leans toward"), ("sib", None, "Similar in library"),
]
# Legacy view kept for callers/tests that read the header list as (sort_key, label) pairs.
_HEADERS = [(sk, label) for _cid, sk, label in _COLUMNS]
_NCOLS = len(_COLUMNS)  # the SUPERSET column count; the empty-state colspan uses the per-render count


def _lean_state(e):
    """(leans_list, reason, missing_reads) for the reference cell. An explicit `_lean_reason`
    (injected by build_catalog) wins; a non-empty `_leans` is always "ok"; otherwise the reason is
    inferred from run mode so unit fixtures that inject no reason still read correctly — a quick row
    is the missing-by-mode "quick" case, a full row defaults to a computed "no-direction" result."""
    leans = e.get("_leans") or []
    if leans:
        return leans, "ok", []
    reason = e.get("_lean_reason")
    if reason:
        return leans, reason, (e.get("_lean_missing") or [])
    return leans, (SC.R_QUICK if e.get("mode") == "quick" else SC.R_NO_DIRECTION), []


def _sib_state(e):
    """(siblings_list, reason, missing_reads) for the own-library cell — same inference contract as
    `_lean_state`, but a full row with no result defaults to the "no-comparison yet" edge (F-INV-7)."""
    sibs = e.get("_siblings") or []
    if sibs:
        return sibs, "ok", []
    reason = e.get("_sib_reason")
    if reason:
        return sibs, reason, (e.get("_sib_missing") or [])
    return sibs, (SC.R_QUICK if e.get("mode") == "quick" else SC.R_NO_COMPARISON), []


# A column carries data (so it renders, D-INV-22 / F-INV-7) when at least one version produced a
# computed RESULT — a hit, a "no close direction"/"no comparison", or a "can't compare". A quick row
# (missing-by-mode) and a no-data row do NOT count, so an all-quick / no-directions library sheds the
# whole column instead of carrying an all-empty one.
_LEAN_RESULT_REASONS = frozenset({"ok", SC.R_NO_DIRECTION, SC.R_MISSING})
_SIB_RESULT_REASONS = frozenset({"ok", SC.R_NO_COMPARISON, SC.R_MISSING})


def _row_id(track: str) -> str:
    """Stable, HTML-id-safe row anchor for a track slug — the sibling chip scrolls to `#<this>`
    (F-INV-4). Non-word chars fold to '-' so any deposited slug yields a valid id/fragment; the same
    helper builds both the `<tr id>` and the chip href so they always match."""
    return "row-" + re.sub(r"[^A-Za-z0-9_-]", "-", str(track or ""))


def _responsive_css(active_ids) -> str:
    """Build the column-shedding media queries from the ACTUAL rendered column order, so the shed
    stays in lock-step when a similarity column is absent (its nth-child position would otherwise
    shift). Priority is unchanged: mood/style + Analysis drop first (≤1440), the reference columns
    only at ≤1100, date at ≤880 (which also tightens padding). A rule is emitted only for columns
    that are actually present."""
    pos = {cid: i + 1 for i, cid in enumerate(active_ids)}

    def sel(ids):
        parts = []
        for cid in ids:
            if cid in pos:
                n = pos[cid]
                parts.append(f"thead th:nth-child({n})")
                parts.append(f"tbody td:nth-child({n})")
        return ",".join(parts)

    blocks = []
    s1 = sel(["tags", "mode"])
    if s1:
        blocks.append(f"@media(max-width:1440px){{{s1}{{display:none}}}}")       # mood/style + mode
    s2 = sel(["lean", "sib"])
    if s2:
        blocks.append(f"@media(max-width:1100px){{{s2}{{display:none}}}}")       # last resort: ref cols
    s3 = sel(["date"])
    date_rule = f"{s3}{{display:none}};" if s3 else ""
    blocks.append(f"@media(max-width:880px){{{date_rule}"
                  f".wrap{{padding:18px 12px 48px}};tbody td,thead th{{padding:6px 8px}}}}")  # date
    return "\n".join(blocks)


def render_catalog_html(entries, *, widgets_rel="widgets", title="Track Coach — Library",
                        migrate_banner: int = 0, missing_banner: int = 0) -> str:
    """Render the whole catalog page from index entries. PURE (no filesystem).

    Sim data (`_lean`, `_siblings`) is expected pre-injected into each entry dict by
    build_catalog (same pattern as `mix_uri`). Gracefully degrades when absent (old entries
    without run dirs show 'no close direction yet' / '—').

    ``migrate_banner``: when > 0, a passive banner is shown prompting the user to run
    ``migrate`` to consolidate analysis data out of Ableton project folders (G-INV-16 support).
    """
    groups = library.group_versions(entries)
    n_tracks = len(groups)  # D-INV-35: one row per track, so the count of rows == the count of tracks

    # Pre-build lookup maps from ALL entries (pure: _open_href is pure).
    # Used to resolve sibling display labels and widget links.
    _title_map = {}
    _href_map = {}
    for e in entries:
        t = e.get("track")
        if t:
            _title_map[t] = e.get("title") or t.replace("_", " ")
            _href_map[t] = _open_href(e, widgets_rel)

    # D-INV-35: one row per track — its NEWEST version (group_versions orders newest-first). Older
    # versions live only in the per-track plaque (INV-11), never as a second catalog row.
    ordered = [(track, groups[track][0]) for track in sorted(groups, key=str.lower)]

    # PRESENCE GATE (D-INV-22 / F-INV-7): the two similarity columns render only when at least one
    # shown version produced a computed RESULT. An all-quick / no-directions library carries no
    # all-empty column — the header and every per-row cell drop together, and the responsive shed +
    # empty-state colspan follow the resulting column count so nothing goes out of lock-step.
    reps = [ver["rep"] for _t, ver in ordered]
    show_lean = any(_lean_state(e)[1] in _LEAN_RESULT_REASONS for e in reps)
    show_sib = any(_sib_state(e)[1] in _SIB_RESULT_REASONS for e in reps)
    active_cols = [(cid, sk, label) for cid, sk, label in _COLUMNS
                   if (cid != "lean" or show_lean) and (cid != "sib" or show_sib)]
    ncols = len(active_cols)

    body_rows = []
    uid = 0
    for track, ver in ordered:
        body_rows.append(_row(track, ver, widgets_rel, uid,  # uid → unique ribbon gradient ids
                              mix_uri=ver["rep"].get("mix_uri"),
                              title_map=_title_map, href_map=_href_map,
                              show_lean=show_lean, show_sib=show_sib))
        uid += 1
    rows_html = "\n".join(body_rows) or (
        f'<tr><td colspan="{ncols}" class="empty">Library is empty — analyse a track to populate it.</td></tr>')
    def _th(cid, k, label):
        # The lean (reference) header carries the `c-lean` hook so the references switch
        # (D-INV-6/23) hides the whole column — header AND cells — together. The §F own-library
        # header ("sib") gets no hook: it is not a reference surface (D-INV-7), never hidden.
        classes = ([ "sortable" ] if k else []) + (["c-lean"] if cid == "lean" else [])
        cls_attr = f' class="{" ".join(classes)}"' if classes else ""
        dk = f' data-key="{k}"' if k else ""
        ar = '<span class="ar"></span>' if k else ""
        return f'<th{cls_attr}{dk}>{html.escape(label)}{ar}</th>'
    ths = "".join(_th(cid, k, label) for cid, k, label in active_cols)
    responsive_css = _responsive_css([cid for cid, _sk, _label in active_cols])
    p = PALETTE
    # G-INV-16/22 passive banners: a member still on disk can be consolidated (migrate); a member
    # whose source is gone can only be deleted or re-analysed — never shown as consolidatable.
    n_outside = migrate_banner
    migrate_html = ""
    if n_outside > 0:
        n_word = f"{n_outside} track{'s' if n_outside != 1 else ''}"
        has_have = "have" if n_outside != 1 else "has"
        migrate_html = (
            f'<div class="migrate-banner">{n_word} {has_have} analysis data in project folders'
            f' — run <code>migrate</code> to consolidate.</div>'
        )
    if missing_banner > 0:
        m_word = f"{missing_banner} track{'s' if missing_banner != 1 else ''}"
        has_have = "have" if missing_banner != 1 else "has"
        migrate_html += (
            f'<div class="missing-banner">{m_word} {has_have} a missing source folder'
            f' — nothing left to consolidate; delete the entry or re-analyse the track.</div>'
        )
    # References show/hide switch (D-INV-6/23): the control renders wherever a reference surface
    # renders — here, only when the reference (leans-toward) column is shown (show_lean). Same label +
    # behaviour + shared flag key as the widget control, so it is ONE named switch across both pages.
    refs_toggle = ('<button id="refsToggle" class="refstoggle" type="button" '
                   'aria-pressed="false">Hide references</button>' if show_lean else "")
    return f"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{html.escape(title)}</title>
<link rel="icon" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'><rect width='32' height='32' rx='7' fill='%230c0e14'/><rect x='6' y='14' width='4' height='12' rx='1.6' fill='%23a78bfa'/><rect x='13' y='7' width='4' height='19' rx='1.6' fill='%234cc9f0'/><rect x='20' y='11' width='4' height='15' rx='1.6' fill='%23ffd166'/></svg>">
<style>
:root{{--bg:{p['bg']};--panel:{p['panel']};--panel2:{p['panel2']};--line:{p['line']};
 --ink:{p['ink']};--muted:{p['muted']};--wob:{p['wob']};--good:{p['good']};--bad:{p['bad']};--bright:{p['bright']}}}
*{{box-sizing:border-box}}
body{{margin:0;background:var(--bg);color:var(--ink);font:14px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}}
.wrap{{max-width:1280px;margin:0 auto;padding:28px 22px 60px}}
h1{{font-size:21px;margin:0 0 2px}}.brand{{color:var(--wob);font-weight:700;font-size:11px;letter-spacing:.12em;text-transform:uppercase}}
.sub{{color:var(--muted);font-size:12.5px;margin:0 0 18px}}
.controls{{display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin-bottom:14px}}
#q{{flex:1;min-width:200px;background:var(--panel);border:1px solid var(--line);border-radius:10px;
 color:var(--ink);padding:9px 13px;font-size:13.5px}}
#q::placeholder{{color:var(--muted)}}
.seg{{display:flex;border:1px solid var(--line);border-radius:10px;overflow:hidden}}
.seg button{{background:var(--panel);color:var(--muted);border:0;padding:9px 14px;font-size:12.5px;cursor:pointer}}
.seg button:hover:not(.on){{color:var(--ink)}}
.seg button.on{{background:var(--panel2);color:var(--ink);box-shadow:0 1px 0 rgba(0,0,0,.3)}}
.count{{color:var(--muted);font-size:12px;margin-left:auto}}
/* References show/hide switch (D-INV-6/23) — the catalog half of the ONE named switch; same label
   + behaviour as the widget's. Pill button matching the surrounding controls; pressed = hidden. */
.refstoggle{{padding:9px 14px;border:1px solid var(--line);border-radius:10px;background:var(--panel);
 color:var(--muted);font:600 12.5px/1 inherit;cursor:pointer;white-space:nowrap}}
.refstoggle:hover,.refstoggle[aria-pressed="true"]{{color:var(--ink);border-color:var(--wob)}}
/* The one global persisted flag (localStorage `tc_refs_hidden`, shared with the widget) rides the
   <body> class `refs-hidden`; it hides the reference (leans-toward) column — header AND cells
   (both carry `c-lean`) — TOGETHER. The §F own-library column (`c-sibs`) is NOT a reference surface
   (D-INV-7) and is deliberately NOT under this hook — it stays visible. */
body.refs-hidden .c-lean{{display:none!important}}
table{{width:100%;border-collapse:collapse;font-size:13px}}
thead th{{text-align:left;color:var(--muted);font-weight:600;font-size:11px;text-transform:uppercase;
 letter-spacing:.05em;padding:8px 10px;border-bottom:1px solid var(--line);white-space:nowrap;position:sticky;top:0;background:var(--bg)}}
th.sortable{{cursor:pointer;user-select:none}}th.sortable:hover{{color:var(--ink)}}
th .ar{{font-size:9px;margin-left:3px;color:var(--wob)}}
th.asc .ar::after{{content:"▲"}}th.desc .ar::after{{content:"▼"}}
tbody td{{padding:6px 10px;border-bottom:1px solid var(--line);vertical-align:middle}}
tbody tr:hover{{background:var(--panel2)}}              /* whole row tints on hover → reads as clickable */
tbody tr:hover .ttl{{color:var(--wob)}}
.tablewrap{{overflow-x:auto;-webkit-overflow-scrolling:touch}}  /* fallback: scroll, never squish */
/* The td stays a normal table-cell (so every column shares one vertical-align baseline and rows can't
   skew); the play button + title live in an INNER flex container, never on the <td> itself. */
.c-track{{max-width:210px}}
.tcell{{display:flex;align-items:center;gap:8px}}
.tmeta{{min-width:0;flex:1}}  /* min-width:0 lets the title ellipsis-truncate inside the flex row */
.cplay{{flex:0 0 auto;width:26px;height:26px;border-radius:50%;border:1px solid var(--line);
 background:var(--panel2);color:var(--ink);cursor:pointer;font-size:10px;line-height:1;padding:0;text-align:center}}
.cplay:hover{{border-color:var(--wob);color:var(--wob)}}
.cplay.playing{{background:var(--wob);color:#0c0e14;border-color:var(--wob)}}
.cplay.dead,.cplay:disabled{{opacity:.4;cursor:not-allowed;border-color:var(--line);color:var(--muted)}}
.cplay.dead:hover,.cplay:disabled:hover{{border-color:var(--line);color:var(--muted)}}
svg.sig.play{{cursor:pointer}}  /* the ribbon doubles as a click-to-seek scrubber when playable */
svg.sig .ph{{pointer-events:none}}
.ttl{{display:block;font-weight:600;color:var(--ink);text-decoration:none;
 overflow:hidden;text-overflow:ellipsis;white-space:nowrap}}
a.ttl:hover{{color:var(--wob);text-decoration:underline}}
.trk{{display:block;color:var(--muted);font-size:10.5px;
 overflow:hidden;text-overflow:ellipsis;white-space:nowrap}}
.c-num{{font-variant-numeric:tabular-nums;white-space:nowrap}}
.c-ver{{color:var(--bright);font-weight:600;white-space:nowrap}}.runs{{color:var(--muted);font-weight:400;font-size:11px}}
.stale{{display:inline-block;margin-left:6px;font-size:9.5px;font-weight:700;text-transform:uppercase;
 letter-spacing:.04em;padding:1px 6px;border-radius:20px;background:rgba(255,180,84,.16);color:var(--warn);cursor:help;white-space:nowrap}}
.c-date,.c-key{{color:var(--muted);white-space:nowrap}}
svg.arc{{width:130px;height:30px;display:block}}.noarc{{color:var(--muted)}}
svg.sig{{width:168px;height:47px;display:block}}.c-sig{{width:168px}}
.delta{{margin-left:5px;font-size:10px;color:var(--muted);font-variant-numeric:tabular-nums}}
.c-tags{{min-width:130px}}  /* room for chips to sit 2-per-row, not one-per-line (keeps rows short) */
.tag{{display:inline-block;font-size:10px;padding:1px 7px;border-radius:20px;margin:1px 3px 1px 0;white-space:nowrap}}
.tag.mood{{background:rgba(167,139,250,.16);color:#cdbcff}}
.tag.style{{background:transparent;border:1px solid var(--line);color:var(--muted)}}
.tag.draft{{background:transparent;border:1px dashed var(--line);color:var(--muted);font-style:italic}}
.mode{{font-size:10.5px;padding:2px 8px;border-radius:20px;text-transform:uppercase;letter-spacing:.04em}}
.mode.full{{background:rgba(70,211,154,.14);color:var(--good)}}.mode.quick{{background:rgba(255,209,102,.14);color:var(--bright)}}
/* Similarity columns (§D.10 / §F — added 2026-06-29) */
.c-sim{{min-width:96px;font-size:11.5px;vertical-align:middle}}
.sim-none{{color:var(--muted);font-style:italic;font-size:11px}}
.sim-dir{{display:block;font-weight:600;text-decoration:none;line-height:1.6}}
.sim-dir:hover{{text-decoration:underline}}
.sib-chip{{display:inline-block;background:var(--panel2);border:1px solid;border-radius:6px;
 padding:1px 7px;margin:0 3px 3px 0;font-size:10.5px;text-decoration:none;white-space:nowrap}}
.sib-chip:hover{{opacity:.85}}
/* Greyscale-safe closeness glyph — filled vs hollow dots carry the cue (D-INV-26). The word rides a
   screen-reader-only span + a title, so the glyph is a redundancy, not the sole carrier (I.10a). */
.dot-tier{{font-size:.82em;letter-spacing:.5px;margin-right:5px;vertical-align:middle}}
.sr-only{{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;
 clip:rect(0,0,0,0);white-space:nowrap;border:0}}
/* Responsive columns: the full table fits only on a wide/maximised window. Drop the LEAST important
   columns FIRST and keep the two similarity columns visible longest — they were
   the ones clipping off-screen at 1400 (Fable pre-1.0 V1). The nth-child positions are generated
   from the ACTUAL rendered column order (a shed similarity column would otherwise shift them out of
   lock-step), priority unchanged: mood/style + mode ≤1440, reference cols ≤1100, date ≤880;
   overflow-x:auto is the last-resort fallback. */
{responsive_css}
/* F-INV-4: a row a sibling chip scrolled to gets a brief highlight pulse — pure navigation feedback,
   no analysis state changes. Two seconds, then it fades back to the normal row. */
tbody tr.row-pulse{{animation:rowpulse 2s ease-out 1}}
@keyframes rowpulse{{0%{{background:rgba(167,139,250,.42)}}100%{{background:transparent}}}}
.empty{{text-align:center;color:var(--muted);padding:40px}}
.foot{{color:var(--muted);font-size:11px;margin-top:18px;text-align:center}}
tr.hide{{display:none}}
.migrate-banner{{background:rgba(255,209,102,.10);border:1px solid rgba(255,209,102,.35);
 border-radius:10px;padding:10px 16px;margin-bottom:14px;font-size:13px;color:var(--bright)}}
.migrate-banner code{{background:rgba(255,209,102,.15);border-radius:4px;padding:1px 5px;
 font-family:monospace;font-size:12px}}
.missing-banner{{background:rgba(255,107,107,.09);border:1px solid rgba(255,107,107,.32);
 border-radius:10px;padding:10px 16px;margin-bottom:14px;font-size:13px;color:var(--bad)}}
</style></head><body>
<svg width="0" height="0" style="position:absolute"><defs>
 <linearGradient id="ag" x1="0" y1="0" x2="0" y2="1">
  <stop offset="0" stop-color="{p['wob']}" stop-opacity=".45"/>
  <stop offset="1" stop-color="{p['wob']}" stop-opacity="0"/></linearGradient></defs></svg>
<div class="wrap">
 <div class="brand">Track Coach</div>
 <h1>Library</h1>
 <p class="sub">{n_tracks} track{'s' if n_tracks!=1 else ''} · newest version shown · click a header to sort, search to filter.</p>
{migrate_html} <div class="controls">
  <input id="q" type="search" placeholder="Search tracks…" autocomplete="off">
  <div class="seg" id="modeseg">
   <button data-mode="" class="on">All</button>
   <button data-mode="full">Full</button>
   <button data-mode="quick">Quick</button>
  </div>
  {refs_toggle}
  <span class="count" id="count"></span>
 </div>
 <div class="tablewrap"><table><thead><tr>{ths}</tr></thead><tbody id="rows">
{rows_html}
 </tbody></table></div>
 <div class="foot">Track Coach library · generated offline · v{html.escape(build_widget.TC_VERSION)}</div>
</div>
<script>
const tbody=document.getElementById("rows");
const rows=()=>Array.from(tbody.querySelectorAll("tr[data-track]"));
let mode="",q="";
function apply(){{
 let shown=0;
 rows().forEach(tr=>{{
  const okMode=!mode||tr.dataset.mode===mode;
  const okQ=!q||tr.dataset.track.includes(q)||(tr.querySelector(".ttl")?.textContent.toLowerCase().includes(q));
  const show=okMode&&okQ;tr.classList.toggle("hide",!show);if(show)shown++;
 }});
 document.getElementById("count").textContent=shown+" shown";
}}
document.getElementById("q").addEventListener("input",e=>{{q=e.target.value.trim().toLowerCase();apply();}});
document.querySelectorAll("#modeseg button").forEach(b=>b.addEventListener("click",()=>{{
 document.querySelectorAll("#modeseg button").forEach(x=>x.classList.remove("on"));
 b.classList.add("on");mode=b.dataset.mode;apply();}}));
// click-to-sort: numeric for bpm/len/lufs/energy, string otherwise; toggle asc/desc
const NUM=new Set(["bpm","len","lufs","energy"]);
document.querySelectorAll("th.sortable").forEach(th=>th.addEventListener("click",()=>{{
 const key=th.dataset.key,asc=!th.classList.contains("asc");
 document.querySelectorAll("th").forEach(x=>x.classList.remove("asc","desc"));
 th.classList.add(asc?"asc":"desc");
 const num=NUM.has(key);
 const sorted=rows().sort((a,b)=>{{
  let x=a.dataset[key]||"",y=b.dataset[key]||"";
  if(num){{x=parseFloat(x);y=parseFloat(y);return asc?x-y:y-x;}}
  return asc?x.localeCompare(y):y.localeCompare(x);
 }});
 sorted.forEach(tr=>tbody.appendChild(tr));
}}));
// ── row preview player: one <audio> per playable row (the original run's web mix). Play/pause from
// the round button; the playhead rides the TIME-axis ribbon; click the ribbon to seek. Offline.
(function(){{
 const SIG_W={SIG_W};
 let cur=null;
 function stop(){{ if(!cur)return; cur.audio.pause(); cur.btn.classList.remove("playing");
   cur.btn.textContent="▶"; cur.ph.setAttribute("visibility","hidden"); cur=null; }}
 function place(o){{ const d=o.audio.duration; if(!d||!isFinite(d))return;
   const x=(o.audio.currentTime/d)*SIG_W; o.ph.setAttribute("x1",x.toFixed(1));
   o.ph.setAttribute("x2",x.toFixed(1)); o.ph.setAttribute("visibility","visible"); }}
 rows().forEach(tr=>{{
  const src=tr.dataset.mix; if(!src)return;
  const btn=tr.querySelector(".cplay"), svg=tr.querySelector("svg.sig.play");
  const ph=svg&&svg.querySelector(".ph"); if(!btn||!svg||!ph)return;
  let audio=null;
  // the mix existed when the catalog was built but may be gone/moved at view time — give feedback
  // instead of a silently dead button (disable + tooltip), per the Ops finding.
  const dead=()=>{{ if(cur&&cur.audio===audio)stop(); btn.disabled=true;
    btn.classList.add("dead"); btn.title="preview unavailable"; btn.textContent="▶"; }};
  const ensure=()=>{{ if(!audio){{ audio=new Audio(src);
    audio.addEventListener("timeupdate",()=>{{ if(cur&&cur.audio===audio)place(cur); }});
    audio.addEventListener("ended",stop); audio.addEventListener("error",dead); }} return audio; }};
  btn.addEventListener("click",e=>{{ e.preventDefault(); e.stopPropagation();
   const a=ensure(); if(cur&&cur.audio===a){{ stop(); return; }} stop();
   a.play().then(()=>{{ cur={{tr,audio:a,btn,ph,svg}}; btn.classList.add("playing");
     btn.textContent="❚❚"; }}).catch(dead); }});
  svg.addEventListener("click",e=>{{ e.stopPropagation(); const a=ensure();
   if(!a.duration||!isFinite(a.duration))return; const r=svg.getBoundingClientRect();
   const f=Math.min(1,Math.max(0,(e.clientX-r.left)/r.width)); a.currentTime=f*a.duration;
   if(cur&&cur.audio===a)place(cur); }});
 }});
}})();
// ── §F own-library sibling navigation (F-INV-4 / D-INV-28): clicking a sibling chip scrolls the
// catalog to that track's row and pulses a highlight — pure navigation, it changes no analysis
// state. (A reference DIRECTION link, by contrast, opens the widget — the two are different.)
(function(){{
 tbody.addEventListener("click",e=>{{
  const chip=e.target.closest("a.sib-chip[data-scroll-row]"); if(!chip)return;
  const id=chip.getAttribute("data-scroll-row"); const row=id&&document.getElementById(id);
  if(!row)return;                                   // target gone — let the href fall through
  e.preventDefault();
  row.scrollIntoView({{behavior:"smooth",block:"center"}});
  row.classList.remove("row-pulse"); void row.offsetWidth; row.classList.add("row-pulse");
 }});
}})();
// ── References show/hide switch (D-INV-6/23). ONE global persisted flag — localStorage
// `tc_refs_hidden` = "1" (hidden) / "0"|absent (shown) — SHARED with a track's widget under the
// SAME key, so hiding references on either surface hides both. Flips `refs-hidden` on <body>; the
// CSS hides the reference (leans-toward) column (header + cells, both `c-lean`). The §F own-library
// column (`c-sibs`) is not a reference surface (D-INV-7) and stays visible. Read on every load, so
// the state persists across reopen. Default = shown (flag absent → visible).
(function(){{var KEY="tc_refs_hidden";var btn=document.getElementById("refsToggle");
 function isHidden(){{try{{return localStorage.getItem(KEY)==="1";}}catch(e){{return false;}}}}
 function paint(h){{document.body.classList.toggle("refs-hidden",h);
  if(!btn)return;btn.setAttribute("aria-pressed",h?"true":"false");
  btn.textContent=h?"Show references":"Hide references";}}
 if(btn)btn.addEventListener("click",function(){{
  var h=!document.body.classList.contains("refs-hidden");
  try{{localStorage.setItem(KEY,h?"1":"0");}}catch(e){{}}paint(h);}});
 paint(isHidden());}})();
apply();
</script></body></html>"""


def _mix_uri_for(e) -> str | None:
    """Absolute file:// URI of the original run's web mix (`<src_run_dir>/mix_web/mix.m4a`) when it
    exists — the one-button catalog player source. None when there's no playable mix (the row then
    renders without a play button — graceful, never a dead control). Touches the filesystem, so it
    lives in the build wrapper, not the pure renderer."""
    sd = e.get("src_run_dir")
    if not sd:
        return None
    mix = Path(sd) / "mix_web" / "mix.m4a"
    return mix.as_uri() if mix.exists() else None


def _load_sim_data(entries: list) -> tuple[dict, dict]:
    """Load reference directions + z-norm params, build z-normalised own-track library.
    Returns (directions_dict, z_library_dict). Both are empty when the reference file is
    absent — sim columns gracefully show 'no close direction yet' / '—' for all rows."""
    if not _REF_FILE.exists():
        return {}, {}
    try:
        raw = json.loads(_REF_FILE.read_text(encoding="utf-8"))
    except Exception:
        return {}, {}
    norm = raw.get("_norm") or {}
    # Replace JSON null with float('nan') so completeness.is_missing() works
    import math
    def _fix_none(v):
        return float("nan") if v is None else v
    directions = {}
    for k, v in raw.items():
        if k.startswith("_") or not isinstance(v, dict):
            continue
        directions[k] = {ax: _fix_none(vv) for ax, vv in v.items()}

    z_library = {}
    # D-INV-35: the catalog shows each track's NEWEST version, so the lean/sibling fingerprint must
    # come from that newest version's run — never an arbitrary older entry (which "last one wins"
    # over raw entries would pick). newest_reps gives one rep entry per track (newest version).
    for key, rep in library.newest_reps(entries).items():
        src = rep.get("src_run_dir")
        if not src:
            continue
        fp = FP.fingerprint_from_run_dir(src)
        if fp and norm:
            z_library[key] = FP.normalize_fingerprint(fp, norm)
    return directions, z_library


def build_catalog(root: Path = None, *, open_browser: bool = False) -> Path:
    """Read index.json, write index.html into the library root. Returns the path."""
    root = Path(root) if root else library.library_root()
    idx = library.load_index(root)
    entries = idx.get("entries", [])
    # Same-song merge (G-INV-23): fold any aliased track onto its canonical slug BEFORE grouping, so
    # two filename identities of one song collapse to a single catalog row (their bounces stay as
    # versions). Pure copy when no aliases are set — nothing else in the pipeline changes.
    entries = library.canonicalize_entries(entries, library.load_aliases(root))

    # The output root for the purposes of G-INV-14 and G-INV-16:
    # library lives at <output_root>/library/; its parent is the output root.
    output_root = root.parent

    for e in entries:
        # Probe each run for a playable web mix (graceful if none).
        e["mix_uri"] = _mix_uri_for(e)

        # G-INV-14: when src_run_dir is missing on disk, inject the library HTML copy path so
        # _open_href can fall back to it (pre-computed here; _open_href stays pure).
        sd = e.get("src_run_dir")
        if sd and not Path(sd).exists():
            widget = e.get("widget", "")
            lib_copy = root / "widgets" / widget
            if lib_copy.exists():
                e["_lib_href"] = lib_copy.as_uri()

    # G-INV-16/22 passive banner: members whose src_run_dir is outside the output root split into
    # two — a source still on disk can be MOVED (consolidate via migrate); a source that is GONE
    # can only be deleted or re-analysed (nothing left to move), so it is never shown as migratable.
    migrate_banner = 0
    missing_banner = 0
    for e in entries:
        sd = e.get("src_run_dir")
        if sd:
            try:
                Path(sd).relative_to(output_root)
            except ValueError:
                if Path(sd).exists():
                    migrate_banner += 1
                else:
                    missing_banner += 1

    # Inject similarity data into entries (same pattern as mix_uri — filesystem probe here, pure
    # renderer reads the pre-computed fields). Each empty result also carries the WHY (reason +
    # missing-signal reads) so the cell can phrase it (quick / can't-compare / no-direction /
    # no-comparison) and the presence gate can drop an all-empty column (D-INV-22 / F-INV-5/6/7).
    directions, z_library = _load_sim_data(entries)
    for e in entries:
        key = e.get("track")
        fp = z_library.get(key)
        is_quick = e.get("mode") == "quick"
        # Reference column.
        if fp is not None and directions:
            leans = SC.leans_toward_topk(fp, directions)  # up to 3, CLOSE/MID only (§D.10.1)
            e["_leans"] = leans
            if leans:
                e["_lean_reason"], e["_lean_missing"] = "ok", []
            else:
                e["_lean_reason"], e["_lean_missing"] = SC.lean_reason(fp, directions)
        else:
            e["_leans"] = []
            if is_quick or fp is None:
                e["_lean_reason"], e["_lean_missing"] = SC.R_QUICK, []
            else:                                         # fingerprint present but no directions defined
                e["_lean_reason"], e["_lean_missing"] = SC.R_NO_DATA, []
        # Own-library column.
        if fp is not None:
            sibs = SC.nearest_own(key, z_library)
            e["_siblings"] = sibs
            if sibs:
                e["_sib_reason"], e["_sib_missing"] = "ok", []
            else:
                e["_sib_reason"], e["_sib_missing"] = SC.sibling_reason(key, z_library)
        else:
            e["_siblings"] = []
            e["_sib_reason"], e["_sib_missing"] = SC.R_QUICK, []

    html_str = render_catalog_html(entries, migrate_banner=migrate_banner,
                                   missing_banner=missing_banner)
    out = root / "index.html"
    root.mkdir(parents=True, exist_ok=True)
    out.write_text(html_str, encoding="utf-8")
    if open_browser:
        # macOS: a NEW window, per the house rule (never just a path / a new tab)
        try:
            subprocess.run(["open", "-na", "Google Chrome", "--args", "--new-window",
                            f"file://{out}"], check=False)
        except OSError:
            pass
    return out


def main():
    ap = argparse.ArgumentParser(prog="catalog", description="render the track-coach library page")
    sub = ap.add_subparsers(dest="cmd", required=True)
    b = sub.add_parser("build", help="regenerate the library index.html from index.json")
    b.add_argument("--open", action="store_true", help="open the page in a new browser window")
    b.set_defaults(func=lambda a: print(build_catalog(open_browser=a.open)))
    args = ap.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
