#!/usr/bin/env python3
"""catalog.py — the VIEW over the global library store.

`library.py` is the store (deposit/list/clean + the pure metric/version helpers); this module is the
front-end: it reads `index.json` and renders ONE self-contained, offline `index.html` — the home base
for a producer's whole body of work. Flat, sortable, searchable table; each row is a VERSION (a
distinct audio bounce, runs collapsed by content hash), with a coloured mini-arc, the spec numbers,
mood/style tags, and cross-version deltas. The catalog is a LOCAL index (INV-17): both the title link
(`_open_href`) and the play button (`_mix_uri_for`) resolve to an absolute `file://` in the ORIGINAL
run dir, where the widget's stems/mix live — the deposited library copy is stem-less. NOT a publishable
/ GitHub Pages artifact; revisit (KI-4 option b) only if the library is ever published.

  catalog.py build [--open]      # regenerate ~/.track-coach/library/index.html

Auto-regenerated by `track_analyzer.py build` after every deposit; also runnable on demand.
Pure stdlib. `render_catalog_html(entries)` is pure (no filesystem) so it's unit-tested.
"""
from __future__ import annotations
import argparse
import html
import json
import re
import subprocess
import sys
from pathlib import Path

import library  # same scripts/ dir; reuses load_index + the pure metric/version helpers
import build_widget  # for TC_VERSION only (stdlib-only import) — stamp the catalog with its version

PALETTE = {  # slim copy of the build_widget dark theme so the catalog feels like the widgets
    "bg": "#0c0e14", "panel": "#141822", "panel2": "#1b2030", "line": "#2a3142",
    "ink": "#e8ecf6", "muted": "#8b94a8", "wob": "#a78bfa", "good": "#46d39a",
    "bad": "#ff6b6b", "bright": "#ffd166",
}


def _fmt_len(s):
    if not isinstance(s, (int, float)):
        return "—"
    return f"{int(s) // 60}:{int(s) % 60:02d}"


def _fmt_date(stamp):
    """`2026-06-18_0748` → `2026-06-18 07:48`; anything else passes through. Uses rsplit on the LAST
    underscore so a stamp that happens to carry more underscores (malformed deposit) formats instead
    of crashing — `d, t = s.split('_')` used to raise 'too many values to unpack'."""
    s = str(stamp or "")
    if "_" in s:
        d, t = s.rsplit("_", 1)
        if len(t) == 4 and t.isdigit():
            return f"{d} {t[:2]}:{t[2:]}"
    return s


def _fmt_num(x, suffix="", dp=0):
    if not isinstance(x, (int, float)):
        return "—"
    return (f"{x:.{dp}f}" if dp else f"{x:.0f}") + suffix


def _delta_html(delta, key, suffix=""):
    """↑/↓ chip vs the previous version (green=down for LUFS isn't implied; just direction)."""
    d = (delta or {}).get(key)
    if not isinstance(d, (int, float)) or abs(d) < 0.05:
        return ""
    arrow = "▲" if d > 0 else "▼"
    return f'<span class="delta">{arrow}{abs(d):.1f}{suffix}</span>'


def arc_svg(arc, w=130, h=30):
    """Inline-SVG sparkline of the energy curve (the Simple hero curve, tiny). Pure string.

    Legacy fallback for OLD index entries that predate the richer row signature (no per-curve /
    tonal data). New entries render the full `signature_svg` instead."""
    vals = [v for v in (arc or []) if isinstance(v, (int, float))]
    if not vals:
        return '<span class="noarc">—</span>'
    n = len(vals)
    pts = [((i / (n - 1) * w if n > 1 else 0), h - v * (h - 3) - 1.5) for i, v in enumerate(vals)]
    line = " ".join(f"{x:.1f},{y:.1f}" for x, y in pts)
    area = f"0,{h} {line} {w},{h}"
    return (f'<svg class="arc" viewBox="0 0 {w} {h}" preserveAspectRatio="none" aria-hidden="true">'
            f'<polygon points="{area}" fill="url(#ag)"/>'
            f'<polyline points="{line}" fill="none" stroke="{PALETTE["wob"]}" stroke-width="1.5"/></svg>')


# ── catalog ROW SIGNATURE (D ribbon + 9-band tonal strip) ───────────────────────────────────
# Decided 2026-06-19 (see memory track-catalog-viz / NEXT_STEPS): one shape that carries real,
# measured-non-redundant info per track, and is fully visible by TAP — no hover, no tooltip.
#   TOP   = spectral ribbon, x = TIME : height=energy, line+fill colour=brightness, weight=density.
#   BOTTOM= 9-band tonal strip, x = FREQUENCY : the widget's own low-red→mid-green→high-blue ramp,
#           bar height ∝ loudness, flagged bands (|dev_db|≥4) brightened.
# The two axes (time vs frequency) are deliberately kept apart by a gap + divider so the cell reads
# as "shape over time" + "spectrum", not one plot.
SIG_W, RIB_H, STRIP_H, GAPV = 168, 30, 12, 5
SIG_H = RIB_H + GAPV + STRIP_H
_DEEP, _GOLD, _COOL = (108, 92, 255), (255, 209, 102), (120, 230, 220)


def _norm(v):
    v = [x for x in v if isinstance(x, (int, float))]
    if not v:
        return []
    lo, hi = min(v), max(v)
    r = (hi - lo) or 1.0
    return [(x - lo) / r for x in v]


def _lerp(a, b, t):
    return tuple(round(a[i] + (b[i] - a[i]) * t) for i in range(3))


def _hexc(c):
    return "#%02x%02x%02x" % tuple(max(0, min(255, int(x))) for x in c)


def _bright_col(t):
    """brightness ramp: deep-violet → gold (t<0.6) → cool teal (t≥0.6)."""
    return _hexc(_lerp(_DEEP, _GOLD, t / 0.6)) if t < 0.6 else _hexc(_lerp(_GOLD, _COOL, (t - 0.6) / 0.4))


def _band_col(t):
    """widget's frequency ramp (build_widget.py): low red → mid green → high blue."""
    if t < 0.5:
        tt = t * 2
        return (255 - tt * (255 - 76), 78 + tt * (214 - 78), 80 + tt * (140 - 80))
    tt = (t - 0.5) * 2
    return (76 - tt * (76 - 80), 214 - tt * (214 - 168), 140 + tt * (255 - 140))


def _poly(P):
    return " ".join(f"{x:.1f},{y:.1f}" for x, y in P)


def _ribbon(energy, brightness, density, uid):
    """The time-shape ribbon. Returns SVG inner string (defs + polygon + polyline), or '' if empty."""
    e = _norm(energy)
    if not e:
        return ""
    b = _norm(brightness) or [0.5] * len(e)
    d = _norm(density) or [0.4] * len(e)
    n = len(e)
    if len(b) != n:  # guard: align colour to the energy curve length
        b = (b + [b[-1]] * n)[:n] if b else [0.5] * n
    dens_avg = (sum(d) / len(d)) if d else 0.4
    pts = [(i / (n - 1) * SIG_W if n > 1 else 0, RIB_H - 2 - c * (RIB_H - 4)) for i, c in enumerate(e)]
    area = f"0,{RIB_H - 2} " + _poly(pts) + f" {SIG_W},{RIB_H - 2}"
    stops = "".join(f'<stop offset="{i / (n - 1) * 100:.1f}%" stop-color="{_bright_col(b[i])}"/>'
                    for i in range(n)) if n > 1 else f'<stop offset="0%" stop-color="{_bright_col(b[0])}"/>'
    fstops = "".join(f'<stop offset="{i / (n - 1) * 100:.1f}%" stop-color="{_bright_col(b[i])}" stop-opacity="0.30"/>'
                     for i in range(n)) if n > 1 else f'<stop offset="0%" stop-color="{_bright_col(b[0])}" stop-opacity="0.30"/>'
    lw = 1.2 + dens_avg * 1.7
    return (f'<defs><linearGradient id="r{uid}" x1="0" x2="1">{stops}</linearGradient>'
            f'<linearGradient id="rf{uid}" x1="0" x2="1">{fstops}</linearGradient></defs>'
            f'<polygon points="{area}" fill="url(#rf{uid})"/>'
            f'<polyline points="{_poly(pts)}" fill="none" stroke="url(#r{uid})" '
            f'stroke-width="{lw:.1f}" stroke-linejoin="round"/>')


def _tonal_strip(tonal):
    """The 9-band spectrum strip (x=frequency). Returns SVG inner string, or '' if no tonal data."""
    rel = [b.get("rel_db", 0) for b in tonal if isinstance(b, dict)]
    dev = [b.get("dev_db", 0) for b in tonal if isinstance(b, dict)]
    if not rel:
        return ""
    lo = min(rel)
    span = max(8.0, -lo)
    n = len(rel)
    gap = 2
    bw = (SIG_W - gap * (n - 1)) / n
    y0 = RIB_H + GAPV
    out = f'<line x1="0" y1="{y0:.1f}" x2="{SIG_W}" y2="{y0:.1f}" stroke="{PALETTE["line"]}" stroke-width="0.6"/>'
    for i, vdb in enumerate(rel):
        x = i * (bw + gap)
        h = max(1.5, (1 - (-vdb / span)) * STRIP_H)  # louder band (rel_db→0) = taller bar
        c = _band_col(i / (n - 1) if n > 1 else 0)
        hot = i < len(dev) and isinstance(dev[i], (int, float)) and abs(dev[i]) >= 4
        op = 0.95 if hot else 0.6
        out += (f'<rect x="{x:.1f}" y="{y0 + (STRIP_H - h):.1f}" width="{bw:.1f}" height="{h:.1f}" '
                f'fill="rgb({int(c[0])},{int(c[1])},{int(c[2])})" opacity="{op}"/>')
    return out


def signature_svg(e, uid=0, playable=False):
    """Full catalog row signature for index entry `e`: spectral ribbon over a 9-band tonal strip.

    Degrades gracefully: ribbon-only when there's no `tonal_balance` (e.g. older entries that still
    have curves); legacy `arc` sparkline when there are no curves at all; '—' when nothing. PURE.

    `playable` (a web mix exists for this row) overlays a click-to-seek area + a playhead line on
    the TIME axis (the ribbon, top) only — never the frequency strip — so the row doubles as a
    one-button preview scrubber (Sasha 2026-06-20: 'ползунок вдоль графика но не вдоль частотной')."""
    energy = e.get("energy") or []
    rib = _ribbon(energy, e.get("brightness") or [], e.get("density") or [], uid)
    if not rib:
        return arc_svg(e.get("arc"))  # no per-curve data → legacy sparkline (or '—')
    strip = _tonal_strip(e.get("tonal_balance") or [])
    h = SIG_H if strip else RIB_H
    if playable:
        scrub = (f'<rect class="scrub" x="0" y="0" width="{SIG_W}" height="{RIB_H}" fill="transparent"/>'
                 f'<line class="ph" x1="0" y1="0" x2="0" y2="{RIB_H}" stroke="{PALETTE["ink"]}" '
                 f'stroke-width="1.4" visibility="hidden"/>')
        return (f'<svg class="sig play" viewBox="0 0 {SIG_W} {h}" preserveAspectRatio="none">'
                f'{rib}{strip}{scrub}</svg>')
    return (f'<svg class="sig" viewBox="0 0 {SIG_W} {h}" preserveAspectRatio="none" aria-hidden="true">'
            f'{rib}{strip}</svg>')


def _tag_chips(mood, style, source):
    chips = "".join(f'<span class="tag mood">{html.escape(str(t))}</span>' for t in (mood or []))
    chips += "".join(f'<span class="tag style">{html.escape(str(t))}</span>' for t in (style or []))
    if not chips:
        return '<span class="noarc">—</span>'
    if source == "heuristic":  # mark drafts so an un-reviewed guess never reads as fact
        chips += '<span class="tag draft" title="heuristic draft — not yet reviewed">draft</span>'
    return chips


def _widget_version(e):
    """The TC_VERSION the linked widget was built on. Prefer the value stored in the index entry at
    deposit time (`tc_version`) — filename-INDEPENDENT, so a stale link is caught even when the filename
    carries no version or a musical one like `v2` (INV-12 option-b / KI-7). Fall back to parsing the
    widget filename (`…_vX.Y.Z.html`) for entries deposited before that field existed. None when neither
    is available — don't cry wolf. PURE. Used to flag a STALE catalog row (INV-12 / KI-1)."""
    tv = (e.get("tc_version") or "").strip()
    if re.fullmatch(r"\d+\.\d+\.\d+", tv):
        return tv
    m = re.search(r"_v(\d+\.\d+\.\d+)\.html$", str(e.get("src_widget") or ""))
    return m.group(1) if m else None


def _stale_chip(e):
    """A small 'stale' marker when the row's linked widget was built on an older TC_VERSION than the
    current one — so an out-of-date deposit is visible, not silently opened (INV-12). '' when current
    or unknown."""
    wv = _widget_version(e)
    if wv and wv != build_widget.TC_VERSION:
        return (f'<span class="stale" title="opens a v{wv} widget; current is '
                f'v{build_widget.TC_VERSION} — re-analyse to refresh">stale</span>')
    return ""


def _open_href(e, widgets_rel):
    """Where 'open →' points. Prefer the ORIGINAL widget in its run dir — its stems sit next to
    it, so the player actually plays. The library copy is stem-less (a deposit is a single .html),
    so opening it leaves a dead player. Fall back to the relative copy for old entries that predate
    `src_widget` (backward-compat). PURE (no filesystem)."""
    src_dir, src_widget = e.get("src_run_dir"), e.get("src_widget")
    if src_dir and src_widget:
        return (Path(src_dir) / src_widget).as_uri()  # absolute file:// (encodes spaces/[brackets])
    widget = e.get("widget", "")
    return f"{widgets_rel}/{widget}" if widget else ""


def _row(track, ver, widgets_rel, uid=0, mix_uri=None):
    e = ver["rep"]
    title = e.get("title") or track.replace("_", " ")
    href = _open_href(e, widgets_rel)
    # The track TITLE is the link into the widget (no separate "open" column any more — Sasha
    # 2026-06-20: "кнопка опен не нужна если сделать само название кликабл"). Whole row tints on
    # hover (CSS) so it reads as clickable; falls back to a plain span when there's no widget.
    ttl = html.escape(str(title))
    title_cell = (f'<a class="ttl" href="{html.escape(href)}">{ttl}</a>' if href
                  else f'<span class="ttl">{ttl}</span>')
    # One-button preview player: only when the original run has a web mix (mix_uri). The button
    # sits left of the title; the scrubber rides the signature ribbon (wired in JS by data-mix).
    play_btn = ('<button class="cplay" type="button" aria-label="Play preview">▶</button>'
                if mix_uri else "")
    # data-* attrs drive client-side sort; numeric ones fall back to -1 so blanks sort last asc
    def num(x):
        return f"{x}" if isinstance(x, (int, float)) else "-1"
    mix_attr = f' data-mix="{html.escape(mix_uri)}"' if mix_uri else ""
    return f"""<tr data-track="{html.escape(track.lower())}" data-mode="{html.escape(e.get('mode',''))}"{mix_attr}
      data-version="{html.escape(str(ver['label']))}" data-date="{html.escape(str(e.get('stamp','')))}"
      data-bpm="{num(e.get('bpm'))}" data-key="{html.escape(str(e.get('key') or ''))}"
      data-len="{num(e.get('length_s'))}" data-lufs="{num(e.get('lufs'))}"
      data-energy="{num(e.get('energy_level'))}">
 <td class="c-track"><div class="tcell">{play_btn}<span class="tmeta">{title_cell}
   <span class="trk">{html.escape(track)}</span></span></div></td>
 <td class="c-ver">{html.escape(str(ver['label']))}{'' if ver['n_runs']<2 else f' <span class=runs>×{ver["n_runs"]}</span>'}{_stale_chip(e)}</td>
 <td class="c-date">{html.escape(_fmt_date(e.get('stamp')))}</td>
 <td class="c-sig">{signature_svg(e, uid, playable=bool(mix_uri))}</td>
 <td class="c-num">{_fmt_num(e.get('bpm'))}{_delta_html(ver.get('delta'),'bpm')}</td>
 <td class="c-key">{html.escape(str(e.get('key') or '—'))}</td>
 <td class="c-num">{_fmt_len(e.get('length_s'))}</td>
 <td class="c-num">{_fmt_num(e.get('lufs'),dp=1)}{_delta_html(ver.get('delta'),'lufs')}</td>
 <td class="c-tags">{_tag_chips(e.get('mood_tags'),e.get('style_tags'),e.get('tags_source'))}</td>
 <td class="c-mode"><span class="mode {html.escape(e.get('mode',''))}">{html.escape(e.get('mode',''))}</span></td>
</tr>"""


# The one-line "verdict" was dropped from the catalog (Sasha 2026-06-20: "колонка вердикт реально
# нужна? она там всё ломает") — it was the widest, most variable column and forced the table off the
# screen. The verdict still lives inside each track's widget; the catalog stays scannable.
_HEADERS = [
    ("track", "Track"), ("version", "Version"), ("date", "Date"), (None, "Signature"),
    ("bpm", "BPM"), ("key", "Key"), ("len", "Length"), ("lufs", "LUFS"),
    (None, "Mood / style"), ("mode", "Mode"),
]
_NCOLS = len(_HEADERS)  # keep the empty-state colspan in lock-step with the header count


def render_catalog_html(entries, *, widgets_rel="widgets", title="Track Coach — Library") -> str:
    """Render the whole catalog page from index entries. PURE (no filesystem)."""
    groups = library.group_versions(entries)
    n_tracks = len(groups)
    n_versions = sum(len(v) for v in groups.values())
    body_rows = []
    uid = 0
    for track in sorted(groups, key=str.lower):
        for ver in groups[track]:
            body_rows.append(_row(track, ver, widgets_rel, uid,  # uid → unique ribbon gradient ids
                                  mix_uri=ver["rep"].get("mix_uri")))
            uid += 1
    rows_html = "\n".join(body_rows) or (
        f'<tr><td colspan="{_NCOLS}" class="empty">Library is empty — analyse a track to populate it.</td></tr>')
    ths = "".join(
        (f'<th class="sortable" data-key="{k}">{html.escape(label)}<span class="ar"></span></th>'
         if k else f'<th>{html.escape(label)}</th>')
        for k, label in _HEADERS)
    p = PALETTE
    return f"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{html.escape(title)}</title>
<link rel="icon" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'><rect width='32' height='32' rx='7' fill='%230c0e14'/><rect x='6' y='14' width='4' height='12' rx='1.6' fill='%23a78bfa'/><rect x='13' y='7' width='4' height='19' rx='1.6' fill='%234cc9f0'/><rect x='20' y='11' width='4' height='15' rx='1.6' fill='%23ffd166'/></svg>">
<style>
:root{{--bg:{p['bg']};--panel:{p['panel']};--panel2:{p['panel2']};--line:{p['line']};
 --ink:{p['ink']};--muted:{p['muted']};--wob:{p['wob']};--good:{p['good']};--bad:{p['bad']};--bright:{p['bright']}}}
*{{box-sizing:border-box}}
body{{margin:0;background:var(--bg);color:var(--ink);font:14px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}}
.wrap{{max-width:1280px;margin:0 auto;padding:28px 22px 60px}}
h1{{font-size:21px;margin:0 0 2px}}.brand{{color:var(--wob);font-weight:700;font-size:11px;letter-spacing:.12em;text-transform:uppercase}}
.sub{{color:var(--muted);font-size:12.5px;margin:0 0 18px}}
.controls{{display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin-bottom:14px}}
#q{{flex:1;min-width:200px;background:var(--panel);border:1px solid var(--line);border-radius:10px;
 color:var(--ink);padding:9px 13px;font-size:13.5px}}
#q::placeholder{{color:var(--muted)}}
.seg{{display:flex;border:1px solid var(--line);border-radius:10px;overflow:hidden}}
.seg button{{background:var(--panel);color:var(--muted);border:0;padding:9px 14px;font-size:12.5px;cursor:pointer}}
.seg button.on{{background:var(--wob);color:#0c0e14;font-weight:700}}
.count{{color:var(--muted);font-size:12px;margin-left:auto}}
table{{width:100%;border-collapse:collapse;font-size:13px}}
thead th{{text-align:left;color:var(--muted);font-weight:600;font-size:11px;text-transform:uppercase;
 letter-spacing:.05em;padding:8px 10px;border-bottom:1px solid var(--line);white-space:nowrap;position:sticky;top:0;background:var(--bg)}}
th.sortable{{cursor:pointer;user-select:none}}th.sortable:hover{{color:var(--ink)}}
th .ar{{font-size:9px;margin-left:3px;color:var(--wob)}}
th.asc .ar::after{{content:"▲"}}th.desc .ar::after{{content:"▼"}}
tbody td{{padding:6px 10px;border-bottom:1px solid var(--line);vertical-align:middle}}
tbody tr:hover{{background:var(--panel2)}}              /* whole row tints on hover → reads as clickable */
tbody tr:hover .ttl{{color:var(--wob)}}
.tablewrap{{overflow-x:auto;-webkit-overflow-scrolling:touch}}  /* fallback: scroll, never squish */
/* The td stays a normal table-cell (so every column shares one vertical-align baseline and rows can't
   skew); the play button + title live in an INNER flex container, never on the <td> itself. */
.c-track{{max-width:250px}}
.tcell{{display:flex;align-items:center;gap:8px}}
.tmeta{{min-width:0;flex:1}}  /* min-width:0 lets the title ellipsis-truncate inside the flex row */
.cplay{{flex:0 0 auto;width:26px;height:26px;border-radius:50%;border:1px solid var(--line);
 background:var(--panel2);color:var(--ink);cursor:pointer;font-size:10px;line-height:1;padding:0;text-align:center}}
.cplay:hover{{border-color:var(--wob);color:var(--wob)}}
.cplay.playing{{background:var(--wob);color:#0c0e14;border-color:var(--wob)}}
.cplay.dead,.cplay:disabled{{opacity:.4;cursor:not-allowed;border-color:var(--line);color:var(--muted)}}
.cplay.dead:hover,.cplay:disabled:hover{{border-color:var(--line);color:var(--muted)}}
svg.sig.play{{cursor:pointer}}  /* the ribbon doubles as a click-to-seek scrubber when playable */
svg.sig .ph{{pointer-events:none}}
.ttl{{display:block;font-weight:600;color:var(--ink);text-decoration:none;
 overflow:hidden;text-overflow:ellipsis;white-space:nowrap}}
a.ttl:hover{{color:var(--wob);text-decoration:underline}}
.trk{{display:block;color:var(--muted);font-size:10.5px;
 overflow:hidden;text-overflow:ellipsis;white-space:nowrap}}
.c-num{{font-variant-numeric:tabular-nums;white-space:nowrap}}
.c-ver{{color:var(--bright);font-weight:600;white-space:nowrap}}.runs{{color:var(--muted);font-weight:400;font-size:11px}}
.stale{{display:inline-block;margin-left:6px;font-size:9.5px;font-weight:700;text-transform:uppercase;
 letter-spacing:.04em;padding:1px 6px;border-radius:20px;background:rgba(255,180,84,.16);color:var(--warn);cursor:help}}
.c-date,.c-key{{color:var(--muted);white-space:nowrap}}
svg.arc{{width:130px;height:30px;display:block}}.noarc{{color:var(--muted)}}
svg.sig{{width:168px;height:47px;display:block}}.c-sig{{width:168px}}
.delta{{margin-left:5px;font-size:10px;color:var(--muted);font-variant-numeric:tabular-nums}}
.c-tags{{min-width:158px}}  /* room for chips to sit 2-per-row, not one-per-line (keeps rows short) */
.tag{{display:inline-block;font-size:10px;padding:1px 7px;border-radius:20px;margin:1px 3px 1px 0;white-space:nowrap}}
.tag.mood{{background:rgba(167,139,250,.16);color:#cdbcff}}
.tag.style{{background:transparent;border:1px solid var(--line);color:var(--muted)}}
.tag.draft{{background:transparent;border:1px dashed var(--line);color:var(--muted);font-style:italic}}
.mode{{font-size:10.5px;padding:2px 8px;border-radius:20px;text-transform:uppercase;letter-spacing:.04em}}
.mode.full{{background:rgba(70,211,154,.14);color:var(--good)}}.mode.quick{{background:rgba(255,209,102,.14);color:var(--bright)}}
/* Responsive columns: on a non-maximised window the 10-col table doesn't fit, and nowrap cells
   would force an ugly horizontal-scroll clip (Sasha 2026-06-20: "если не на полный экран таблица
   странно показывается"). Progressively drop the least-important columns — mood/style + mode → date —
   keeping the core spec (signature, BPM, key, length, LUFS). overflow-x:auto is the last-resort
   fallback below the smallest breakpoint. */
@media(max-width:1100px){{thead th:nth-child(9),tbody td:nth-child(9),
 thead th:nth-child(10),tbody td:nth-child(10){{display:none}}}}                              /* mood/style + mode */
@media(max-width:880px){{thead th:nth-child(3),tbody td:nth-child(3){{display:none}};
 .wrap{{padding:18px 12px 48px}};tbody td,thead th{{padding:6px 8px}}}}                        /* date */
.empty{{text-align:center;color:var(--muted);padding:40px}}
.foot{{color:var(--muted);font-size:11px;margin-top:18px;text-align:center}}
tr.hide{{display:none}}
</style></head><body>
<svg width="0" height="0" style="position:absolute"><defs>
 <linearGradient id="ag" x1="0" y1="0" x2="0" y2="1">
  <stop offset="0" stop-color="{p['wob']}" stop-opacity=".45"/>
  <stop offset="1" stop-color="{p['wob']}" stop-opacity="0"/></linearGradient></defs></svg>
<div class="wrap">
 <div class="brand">Track Coach</div>
 <h1>Library</h1>
 <p class="sub">{n_versions} version{'s' if n_versions!=1 else ''} across {n_tracks} track{'s' if n_tracks!=1 else ''} · click a header to sort, search to filter.</p>
 <div class="controls">
  <input id="q" type="search" placeholder="Search tracks…" autocomplete="off">
  <div class="seg" id="modeseg">
   <button data-mode="" class="on">All</button>
   <button data-mode="full">Full</button>
   <button data-mode="quick">Quick</button>
  </div>
  <span class="count" id="count"></span>
 </div>
 <div class="tablewrap"><table><thead><tr>{ths}</tr></thead><tbody id="rows">
{rows_html}
 </tbody></table></div>
 <div class="foot">Track Coach library · generated offline · v{html.escape(build_widget.TC_VERSION)} · links are relative to <code>{html.escape(widgets_rel)}/</code></div>
</div>
<script>
const tbody=document.getElementById("rows");
const rows=()=>Array.from(tbody.querySelectorAll("tr[data-track]"));
let mode="",q="";
function apply(){{
 let shown=0;
 rows().forEach(tr=>{{
  const okMode=!mode||tr.dataset.mode===mode;
  const okQ=!q||tr.dataset.track.includes(q)||(tr.querySelector(".ttl")?.textContent.toLowerCase().includes(q));
  const show=okMode&&okQ;tr.classList.toggle("hide",!show);if(show)shown++;
 }});
 document.getElementById("count").textContent=shown+" shown";
}}
document.getElementById("q").addEventListener("input",e=>{{q=e.target.value.trim().toLowerCase();apply();}});
document.querySelectorAll("#modeseg button").forEach(b=>b.addEventListener("click",()=>{{
 document.querySelectorAll("#modeseg button").forEach(x=>x.classList.remove("on"));
 b.classList.add("on");mode=b.dataset.mode;apply();}}));
// click-to-sort: numeric for bpm/len/lufs/energy, string otherwise; toggle asc/desc
const NUM=new Set(["bpm","len","lufs","energy"]);
document.querySelectorAll("th.sortable").forEach(th=>th.addEventListener("click",()=>{{
 const key=th.dataset.key,asc=!th.classList.contains("asc");
 document.querySelectorAll("th").forEach(x=>x.classList.remove("asc","desc"));
 th.classList.add(asc?"asc":"desc");
 const num=NUM.has(key);
 const sorted=rows().sort((a,b)=>{{
  let x=a.dataset[key]||"",y=b.dataset[key]||"";
  if(num){{x=parseFloat(x);y=parseFloat(y);return asc?x-y:y-x;}}
  return asc?x.localeCompare(y):y.localeCompare(x);
 }});
 sorted.forEach(tr=>tbody.appendChild(tr));
}}));
// ── row preview player: one <audio> per playable row (the original run's web mix). Play/pause from
// the round button; the playhead rides the TIME-axis ribbon; click the ribbon to seek. Offline.
(function(){{
 const SIG_W={SIG_W};
 let cur=null;
 function stop(){{ if(!cur)return; cur.audio.pause(); cur.btn.classList.remove("playing");
   cur.btn.textContent="▶"; cur.ph.setAttribute("visibility","hidden"); cur=null; }}
 function place(o){{ const d=o.audio.duration; if(!d||!isFinite(d))return;
   const x=(o.audio.currentTime/d)*SIG_W; o.ph.setAttribute("x1",x.toFixed(1));
   o.ph.setAttribute("x2",x.toFixed(1)); o.ph.setAttribute("visibility","visible"); }}
 rows().forEach(tr=>{{
  const src=tr.dataset.mix; if(!src)return;
  const btn=tr.querySelector(".cplay"), svg=tr.querySelector("svg.sig.play");
  const ph=svg&&svg.querySelector(".ph"); if(!btn||!svg||!ph)return;
  let audio=null;
  // the mix existed when the catalog was built but may be gone/moved at view time — give feedback
  // instead of a silently dead button (disable + tooltip), per the Ops finding.
  const dead=()=>{{ if(cur&&cur.audio===audio)stop(); btn.disabled=true;
    btn.classList.add("dead"); btn.title="preview unavailable"; btn.textContent="▶"; }};
  const ensure=()=>{{ if(!audio){{ audio=new Audio(src);
    audio.addEventListener("timeupdate",()=>{{ if(cur&&cur.audio===audio)place(cur); }});
    audio.addEventListener("ended",stop); audio.addEventListener("error",dead); }} return audio; }};
  btn.addEventListener("click",e=>{{ e.preventDefault(); e.stopPropagation();
   const a=ensure(); if(cur&&cur.audio===a){{ stop(); return; }} stop();
   a.play().then(()=>{{ cur={{tr,audio:a,btn,ph,svg}}; btn.classList.add("playing");
     btn.textContent="❚❚"; }}).catch(dead); }});
  svg.addEventListener("click",e=>{{ e.stopPropagation(); const a=ensure();
   if(!a.duration||!isFinite(a.duration))return; const r=svg.getBoundingClientRect();
   const f=Math.min(1,Math.max(0,(e.clientX-r.left)/r.width)); a.currentTime=f*a.duration;
   if(cur&&cur.audio===a)place(cur); }});
 }});
}})();
apply();
</script></body></html>"""


def _mix_uri_for(e) -> str | None:
    """Absolute file:// URI of the original run's web mix (`<src_run_dir>/mix_web/mix.m4a`) when it
    exists — the one-button catalog player source. None when there's no playable mix (the row then
    renders without a play button — graceful, never a dead control). Touches the filesystem, so it
    lives in the build wrapper, not the pure renderer."""
    sd = e.get("src_run_dir")
    if not sd:
        return None
    mix = Path(sd) / "mix_web" / "mix.m4a"
    return mix.as_uri() if mix.exists() else None


def build_catalog(root: Path = None, *, open_browser: bool = False) -> Path:
    """Read index.json, write index.html into the library root. Returns the path."""
    root = Path(root) if root else library.library_root()
    idx = library.load_index(root)
    entries = idx.get("entries", [])
    for e in entries:                      # probe each run for a playable web mix (graceful if none)
        e["mix_uri"] = _mix_uri_for(e)
    html_str = render_catalog_html(entries)
    out = root / "index.html"
    root.mkdir(parents=True, exist_ok=True)
    out.write_text(html_str, encoding="utf-8")
    if open_browser:
        # macOS: a NEW window, per the house rule (never just a path / a new tab)
        try:
            subprocess.run(["open", "-na", "Google Chrome", "--args", "--new-window",
                            f"file://{out}"], check=False)
        except OSError:
            pass
    return out


def main():
    ap = argparse.ArgumentParser(prog="catalog", description="render the track-coach library page")
    sub = ap.add_subparsers(dest="cmd", required=True)
    b = sub.add_parser("build", help="regenerate the library index.html from index.json")
    b.add_argument("--open", action="store_true", help="open the page in a new browser window")
    b.set_defaults(func=lambda a: print(build_catalog(open_browser=a.open)))
    args = ap.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
